generators:
  - git:
      repoURL: https://github.com/mahmoudSh58/gitops_nodjsapp_sandbox.git
      revision: main
      files:
        - path: namespaces/*.yaml

template:
  metadata:
    name: '{{ namespace }}'
  spec:
    project: default
    source:
      repoURL: https://github.com/mahmoudSh58/gitops_nodjsapp_sandbox.git
      targetRevision: main
      path: nodejs-app
      helm:
        valueFiles:
          - '{{path}}'
    destination:
      server: https://kubernetes.default.svc
      namespace: '{{ namespace }}'
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true